// Code generated by go-swagger; DO NOT EDIT.

package burgers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/haroundjudzman/golang-microservice/sdk/models"
)

// NewCreateBurgerParams creates a new CreateBurgerParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateBurgerParams() *CreateBurgerParams {
	return &CreateBurgerParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateBurgerParamsWithTimeout creates a new CreateBurgerParams object
// with the ability to set a timeout on a request.
func NewCreateBurgerParamsWithTimeout(timeout time.Duration) *CreateBurgerParams {
	return &CreateBurgerParams{
		timeout: timeout,
	}
}

// NewCreateBurgerParamsWithContext creates a new CreateBurgerParams object
// with the ability to set a context for a request.
func NewCreateBurgerParamsWithContext(ctx context.Context) *CreateBurgerParams {
	return &CreateBurgerParams{
		Context: ctx,
	}
}

// NewCreateBurgerParamsWithHTTPClient creates a new CreateBurgerParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateBurgerParamsWithHTTPClient(client *http.Client) *CreateBurgerParams {
	return &CreateBurgerParams{
		HTTPClient: client,
	}
}

/* CreateBurgerParams contains all the parameters to send to the API endpoint
   for the create burger operation.

   Typically these are written to a http.Request.
*/
type CreateBurgerParams struct {

	/* Body.

	     Burger data structure to Create or Edit.
	ID field is ignored by both operations
	*/
	Body *models.Burger

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create burger params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateBurgerParams) WithDefaults() *CreateBurgerParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create burger params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateBurgerParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create burger params
func (o *CreateBurgerParams) WithTimeout(timeout time.Duration) *CreateBurgerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create burger params
func (o *CreateBurgerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create burger params
func (o *CreateBurgerParams) WithContext(ctx context.Context) *CreateBurgerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create burger params
func (o *CreateBurgerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create burger params
func (o *CreateBurgerParams) WithHTTPClient(client *http.Client) *CreateBurgerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create burger params
func (o *CreateBurgerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create burger params
func (o *CreateBurgerParams) WithBody(body *models.Burger) *CreateBurgerParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create burger params
func (o *CreateBurgerParams) SetBody(body *models.Burger) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateBurgerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
