// Code generated by go-swagger; DO NOT EDIT.

package burgers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/haroundjudzman/golang-microservice/sdk/models"
)

// DeleteBurgerReader is a Reader for the DeleteBurger structure.
type DeleteBurgerReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteBurgerReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteBurgerNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewDeleteBurgerNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteBurgerInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteBurgerNoContent creates a DeleteBurgerNoContent with default headers values
func NewDeleteBurgerNoContent() *DeleteBurgerNoContent {
	return &DeleteBurgerNoContent{}
}

/* DeleteBurgerNoContent describes a response with status code 204, with default header values.

No content is returned
*/
type DeleteBurgerNoContent struct {
}

func (o *DeleteBurgerNoContent) Error() string {
	return fmt.Sprintf("[DELETE /product/{id}][%d] deleteBurgerNoContent ", 204)
}

func (o *DeleteBurgerNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteBurgerNotFound creates a DeleteBurgerNotFound with default headers values
func NewDeleteBurgerNotFound() *DeleteBurgerNotFound {
	return &DeleteBurgerNotFound{}
}

/* DeleteBurgerNotFound describes a response with status code 404, with default header values.

No matching burger is found
*/
type DeleteBurgerNotFound struct {
}

func (o *DeleteBurgerNotFound) Error() string {
	return fmt.Sprintf("[DELETE /product/{id}][%d] deleteBurgerNotFound ", 404)
}

func (o *DeleteBurgerNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteBurgerInternalServerError creates a DeleteBurgerInternalServerError with default headers values
func NewDeleteBurgerInternalServerError() *DeleteBurgerInternalServerError {
	return &DeleteBurgerInternalServerError{}
}

/* DeleteBurgerInternalServerError describes a response with status code 500, with default header values.

Generic error
*/
type DeleteBurgerInternalServerError struct {
	Payload *models.GenericError
}

func (o *DeleteBurgerInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /product/{id}][%d] deleteBurgerInternalServerError  %+v", 500, o.Payload)
}
func (o *DeleteBurgerInternalServerError) GetPayload() *models.GenericError {
	return o.Payload
}

func (o *DeleteBurgerInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
