// Code generated by go-swagger; DO NOT EDIT.

package burgers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDeleteBurgerParams creates a new DeleteBurgerParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteBurgerParams() *DeleteBurgerParams {
	return &DeleteBurgerParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteBurgerParamsWithTimeout creates a new DeleteBurgerParams object
// with the ability to set a timeout on a request.
func NewDeleteBurgerParamsWithTimeout(timeout time.Duration) *DeleteBurgerParams {
	return &DeleteBurgerParams{
		timeout: timeout,
	}
}

// NewDeleteBurgerParamsWithContext creates a new DeleteBurgerParams object
// with the ability to set a context for a request.
func NewDeleteBurgerParamsWithContext(ctx context.Context) *DeleteBurgerParams {
	return &DeleteBurgerParams{
		Context: ctx,
	}
}

// NewDeleteBurgerParamsWithHTTPClient creates a new DeleteBurgerParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteBurgerParamsWithHTTPClient(client *http.Client) *DeleteBurgerParams {
	return &DeleteBurgerParams{
		HTTPClient: client,
	}
}

/* DeleteBurgerParams contains all the parameters to send to the API endpoint
   for the delete burger operation.

   Typically these are written to a http.Request.
*/
type DeleteBurgerParams struct {

	/* ID.

	   ID of the burger needed for operations

	   Format: int64
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete burger params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteBurgerParams) WithDefaults() *DeleteBurgerParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete burger params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteBurgerParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete burger params
func (o *DeleteBurgerParams) WithTimeout(timeout time.Duration) *DeleteBurgerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete burger params
func (o *DeleteBurgerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete burger params
func (o *DeleteBurgerParams) WithContext(ctx context.Context) *DeleteBurgerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete burger params
func (o *DeleteBurgerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete burger params
func (o *DeleteBurgerParams) WithHTTPClient(client *http.Client) *DeleteBurgerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete burger params
func (o *DeleteBurgerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete burger params
func (o *DeleteBurgerParams) WithID(id int64) *DeleteBurgerParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete burger params
func (o *DeleteBurgerParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteBurgerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
