// Code generated by go-swagger; DO NOT EDIT.

package burgers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/haroundjudzman/golang-microservice/sdk/models"
)

// ListBurgersReader is a Reader for the ListBurgers structure.
type ListBurgersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListBurgersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListBurgersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListBurgersOK creates a ListBurgersOK with default headers values
func NewListBurgersOK() *ListBurgersOK {
	return &ListBurgersOK{}
}

/* ListBurgersOK describes a response with status code 200, with default header values.

List of all burgers
*/
type ListBurgersOK struct {
	Payload []*models.Burger
}

func (o *ListBurgersOK) Error() string {
	return fmt.Sprintf("[GET /burgers][%d] listBurgersOK  %+v", 200, o.Payload)
}
func (o *ListBurgersOK) GetPayload() []*models.Burger {
	return o.Payload
}

func (o *ListBurgersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
