// Code generated by go-swagger; DO NOT EDIT.

package burgers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewListBurgerParams creates a new ListBurgerParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListBurgerParams() *ListBurgerParams {
	return &ListBurgerParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListBurgerParamsWithTimeout creates a new ListBurgerParams object
// with the ability to set a timeout on a request.
func NewListBurgerParamsWithTimeout(timeout time.Duration) *ListBurgerParams {
	return &ListBurgerParams{
		timeout: timeout,
	}
}

// NewListBurgerParamsWithContext creates a new ListBurgerParams object
// with the ability to set a context for a request.
func NewListBurgerParamsWithContext(ctx context.Context) *ListBurgerParams {
	return &ListBurgerParams{
		Context: ctx,
	}
}

// NewListBurgerParamsWithHTTPClient creates a new ListBurgerParams object
// with the ability to set a custom HTTPClient for a request.
func NewListBurgerParamsWithHTTPClient(client *http.Client) *ListBurgerParams {
	return &ListBurgerParams{
		HTTPClient: client,
	}
}

/* ListBurgerParams contains all the parameters to send to the API endpoint
   for the list burger operation.

   Typically these are written to a http.Request.
*/
type ListBurgerParams struct {

	/* ID.

	   ID of the burger needed for operations

	   Format: int64
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list burger params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListBurgerParams) WithDefaults() *ListBurgerParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list burger params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListBurgerParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list burger params
func (o *ListBurgerParams) WithTimeout(timeout time.Duration) *ListBurgerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list burger params
func (o *ListBurgerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list burger params
func (o *ListBurgerParams) WithContext(ctx context.Context) *ListBurgerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list burger params
func (o *ListBurgerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list burger params
func (o *ListBurgerParams) WithHTTPClient(client *http.Client) *ListBurgerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list burger params
func (o *ListBurgerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the list burger params
func (o *ListBurgerParams) WithID(id int64) *ListBurgerParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the list burger params
func (o *ListBurgerParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *ListBurgerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
