// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Burger Burger Burger Burger defines structure for API data
// The burgers are from Bob's Burgers
//
// swagger:model Burger
type Burger struct {

	// Episode when the burger appears
	// Minimum: 1
	Episode int64 `json:"episode,omitempty"`

	// ID of the burger
	// Minimum: 1
	ID int64 `json:"id,omitempty"`

	// Name of the burger
	// Required: true
	// Max Length: 255
	Name *string `json:"name"`

	// Price of the burger
	// Required: true
	// Minimum: 0.01
	Price *float32 `json:"price"`

	// Season when the burger appears
	// Minimum: 1
	Season int64 `json:"season,omitempty"`
}

// Validate validates this burger
func (m *Burger) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEpisode(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePrice(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSeason(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Burger) validateEpisode(formats strfmt.Registry) error {
	if swag.IsZero(m.Episode) { // not required
		return nil
	}

	if err := validate.MinimumInt("episode", "body", m.Episode, 1, false); err != nil {
		return err
	}

	return nil
}

func (m *Burger) validateID(formats strfmt.Registry) error {
	if swag.IsZero(m.ID) { // not required
		return nil
	}

	if err := validate.MinimumInt("id", "body", m.ID, 1, false); err != nil {
		return err
	}

	return nil
}

func (m *Burger) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	if err := validate.MaxLength("name", "body", *m.Name, 255); err != nil {
		return err
	}

	return nil
}

func (m *Burger) validatePrice(formats strfmt.Registry) error {

	if err := validate.Required("price", "body", m.Price); err != nil {
		return err
	}

	if err := validate.Minimum("price", "body", float64(*m.Price), 0.01, false); err != nil {
		return err
	}

	return nil
}

func (m *Burger) validateSeason(formats strfmt.Registry) error {
	if swag.IsZero(m.Season) { // not required
		return nil
	}

	if err := validate.MinimumInt("season", "body", m.Season, 1, false); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this burger based on context it is used
func (m *Burger) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Burger) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Burger) UnmarshalBinary(b []byte) error {
	var res Burger
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
